services:
  - type: web
    name: soundify
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PCLOUD_TOKEN
        value: your-pcloud-token-here
      - key: PCLOUD_FOLDER_ID
        value: your-folder-id-here
    autoDeploy: true
    region: oregon
